# Generated by Django 5.0.3 on 2024-03-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pmid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
