# Generated by Django 5.0.3 on 2024-03-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_pmid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
