# Generated by Django 5.0.3 on 2024-03-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_paper_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='papers',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='categories',
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='categories',
            field=models.ManyToManyField(related_name='papers', to='papers.tag'),
        ),
    ]
