# Generated by Django 5.0.3 on 2024-04-01 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_remove_tag_papers_remove_paper_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_topics', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lda_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='papers.ldamodel')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='papers.topic'),
        ),
    ]
